# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Test connectivity to gateway server
        run: |
          sleep 5
          ssh williamf29@185.36.231.235 'ls'
      - name: Connect to Relay Server
        uses: edipizarro/runner-open-ssh@main
        with:
          sshPublicKey: ${{ secrets.GATEWAY_PBK }}   # Your personal public key (for you to connect)
          gatewayPrivateKey: ${{ secrets.GATEWAY_PVK }} # Your server's private key
          gatewayIP: ${{ secrets.GATEWAY_IP }}          # Your server's public IP
          maxLifeTime: 600      
